{"name": "test_delete_order", "status": "broken", "statusDetails": {"message": "requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)", "trace": "../.venv/lib/python3.11/site-packages/requests/models.py:974: in json\n    return complexjson.loads(self.text, **kwargs)\n        kwargs     = {}\n        self       = <Response [204]>\n/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py:346: in loads\n    return _default_decoder.decode(s)\n        cls        = None\n        kw         = {}\n        object_hook = None\n        object_pairs_hook = None\n        parse_constant = None\n        parse_float = None\n        parse_int  = None\n        s          = ''\n/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:337: in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n        _w         = <built-in method match of re.Pattern object at 0x10a0ac860>\n        s          = ''\n        self       = <json.decoder.JSONDecoder object at 0x10a0bd090>\n/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:355: in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\nE   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n        idx        = 0\n        s          = ''\n        self       = <json.decoder.JSONDecoder object at 0x10a0bd090>\n\nDuring handling of the above exception, another exception occurred:\ntest_orders.py:62: in test_delete_order\n    assert response.json() == {}\n        create_order = {'id': 5, 'quantity': 13.0, 'status': 'pending', 'stocks': 'EURUSD'}\n        http_client = <src.http_client.HttpClient object at 0x10b239f10>\n        order      = {'id': 5, 'quantity': 13.0, 'status': 'pending', 'stocks': 'EURUSD'}\n        response   = <Response [204]>\n        self       = <test_orders.TestOrders object at 0x10b293050>\n../.venv/lib/python3.11/site-packages/requests/models.py:978: in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\nE   requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n        kwargs     = {}\n        self       = <Response [204]>"}, "steps": [{"name": "Send request HttpMethods.DELETE on http://127.0.0.1:8000/orders/5", "status": "passed", "start": 1716289180043, "stop": 1716289180985}], "attachments": [{"name": "log", "source": "7d98284c-7d8d-4874-8a80-1f97224af37a-attachment.txt", "type": "text/plain"}], "start": 1716289180043, "stop": 1716289180985, "uuid": "06cb8daf-669b-432a-936f-0d2f636bd0a0", "historyId": "470cfc83697b96edc227c3a8fec89bb9", "testCaseId": "470cfc83697b96edc227c3a8fec89bb9", "fullName": "tests.test_orders.TestOrders#test_delete_order", "labels": [{"name": "suite", "value": "DELETE"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestOrders"}, {"name": "host", "value": "MacBook-Pro-NikMac.local"}, {"name": "thread", "value": "4636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_orders"}]}